### ISSUE TITLE
Timeout exception when trying to access Kafka state store data

### ISSUE THREAD

**Issue by pavankjadda** [pavankjadda/KafkaStream-CQRS-EventSourcing#10]
Timeout exception when trying to access Kafka state store data from Jersey REST API

```

01:17:59.807 [Connector-Scheduler-4e28bdd1-1] DEBUG org.eclipse.jetty.io.IdleTimeout - SocketChannelEndPoint@33e06565{/127.0.0.1:56848<->/127.0.0.1:8095,OPEN,fill=-,flush=-,to=30004/30000}{io=0/0,kio=0,kro=1}->HttpConnection@3947d220[p=HttpParser{s=CONTENT,0 of -1},g=HttpGenerator@1359336e{s=START}]=>HttpChannelOverHttp@385f66ed{s=HttpChannelState@422baab2{s=HANDLING rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=1,c=false/false,a=HANDLING,uri=//localhost:8095/store/customers,age=210041} idle timeout expired
01:17:59.808 [Connector-Scheduler-4e28bdd1-1] DEBUG org.eclipse.jetty.io.FillInterest - onFail FillInterest@140825f7{null}
java.util.concurrent.TimeoutException: Idle timeout expired: 30003/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
01:17:59.808 [Connector-Scheduler-4e28bdd1-1] DEBUG org.eclipse.jetty.io.WriteFlusher - ignored: WriteFlusher@7360f3f0{IDLE}->null
java.util.concurrent.TimeoutException: Idle timeout expired: 30003/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
01:17:59.809 [Connector-Scheduler-4e28bdd1-1] DEBUG org.eclipse.jetty.io.AbstractEndPoint - Ignored idle endpoint SocketChannelEndPoint@33e06565{/127.0.0.1:56848<->/127.0.0.1:8095,OPEN,fill=-,flush=-,to=30005/30000}{io=0/0,kio=0,kro=1}->HttpConnection@3947d220[p=HttpParser{s=CONTENT,0 of -1},g=HttpGenerator@1359336e{s=START}]=>HttpChannelOverHttp@385f66ed{s=HttpChannelState@422baab2{s=HANDLING rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=1,c=false/false,a=HANDLING,uri=//localhost:8095/store/customers,age=210042}
```

**Comment by pavankjadda** [comment]
The issue is caused by **The state store, customer-store, may have migrated to another instance.**

**Comment by pavankjadda** [comment]
Root cause of the issue: Make sure to create all the topics

1. customer
2. order
3. customer-order
4. order-to-ktable
5. greetings
6. customer-to-ktable-topic
